FROM node:20.12.0-alpine3.19

WORKDIR /user/src/app

COPY package.json package-lock.json tsconfig.json turbo.json ./

COPY apps ./apps
COPY packages ./packages

#instll dependencies

RUN npm install
RUN npm run db:generate

RUN npm run build

CMD [ "npm" ,"run","start" ]